spring:
  application:
    name: ostock-configuration-server
server:
  port: 8888
---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

---

spring:
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/navkkrnair/ostock-configurations.git
          search-paths: main
encrypt:
  key: secretKey